name: test
on:
    push:
        branches-ignore: ['main']

jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: node 18
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: build
              run: |
                  npm ci && npm run build

            - name: check
              run: |
                  npm run check

            - name: lint
              run: |
                  npm run lint
